-- SQL Script to insert new products
-- Τα IDs έχουν μορφή <category><number>, π.χ. coffee01, coffee02 κλπ

INSERT INTO products (id, name, price, category, image_url) VALUES 
('coffee01', 'Espresso', 1.60, 'coffee', '/images/banner.jpg'),
('coffee02', 'Espresso Διπλό', 2.20, 'coffee', '/images/banner.jpg'),
('coffee03', 'Espresso Machiato', 1.80, 'coffee', '/images/banner.jpg'),
('coffee04', 'Americano Μονό', 1.60, 'coffee', '/images/banner.jpg'),
('coffee05', 'Americano Διπλό', 2.20, 'coffee', '/images/banner.jpg'),
('coffee06', 'Freddo Espresso', 2.20, 'coffee', '/images/banner.jpg'),
('coffee07', 'Freddo Espresso 3/Δόσεις', 3.00, 'coffee', '/images/banner.jpg'),
('coffee08', 'Freddo Espresso 4/Δόσεις', 3.20, 'coffee', '/images/banner.jpg'),
('coffee09', 'Freddo Cappuccino', 2.30, 'coffee', '/images/banner.jpg'),
('coffee10', 'Capuccino Διπλό', 2.50, 'coffee', '/images/banner.jpg'),
('coffee11', 'Capuccino Σαντιγύ', 2.80, 'coffee', '/images/banner.jpg'),
('coffee12', 'Capuccino Latte', 2.20, 'coffee', '/images/banner.jpg'),
('coffee13', 'Nescafe', 2.00, 'coffee', '/images/banner.jpg'),
('coffee14', 'Nescafe Decafeine', 2.00, 'coffee', '/images/banner.jpg'),
('coffee15', 'Frappe', 2.00, 'coffee', '/images/banner.jpg'),
('coffee16', 'Ole', 1.60, 'coffee', '/images/banner.jpg'),
('coffee17', 'Φίλτρου', 2.20, 'coffee', '/images/banner.jpg'),
('coffee18', 'Φίλτρου με γεύση', 2.40, 'coffee', '/images/banner.jpg'),
('coffee19', 'Ελληνικός', 1.60, 'coffee', '/images/banner.jpg'),
('coffee20', 'Ελληνικός Διπλός', 2.00, 'coffee', '/images/banner.jpg'),
('chocolates01', 'Σοκολάτα (ζεστή-κρύα)', 3.00, 'chocolates', '/images/banner.jpg'),
('chocolates02', 'Σοκολάτα Λευκή (ζεστή-κρύα)', 3.00, 'chocolates', '/images/banner.jpg'),
('chocolates03', 'Σοκολάτα Vienua', 3.30, 'chocolates', '/images/banner.jpg'),
('chocolates04', 'Σοκολάτα Bueno', 3.20, 'chocolates', '/images/banner.jpg'),
('chocolates05', 'Σοκολάτα OREO', 3.20, 'chocolates', '/images/banner.jpg'),
('chocolates06', 'Σοκολάτα Βανίλια-Φράουλα', 3.20, 'chocolates', '/images/banner.jpg'),
('chocolates07', 'Σοκολάτα Μπανάνα', 3.20, 'chocolates', '/images/banner.jpg'),
('chocolates08', 'Σοκολάτα Μηχανής', 3.00, 'chocolates', '/images/banner.jpg'),
('chocolates09', 'Σοκολάτα με γεύση', 3.20, 'chocolates', '/images/banner.jpg'),
('chocolates10', 'Κακάο', 2.20, 'chocolates', '/images/banner.jpg'),
('rofimata01', 'Freddoccino', 3.50, 'rofimata', '/images/banner.jpg'),
('rofimata02', 'Mochaccino', 3.50, 'rofimata', '/images/banner.jpg'),
('rofimata03', 'Smoothies', 3.50, 'rofimata', '/images/banner.jpg'),
('rofimata04', 'Γρανίτες', 3.00, 'rofimata', '/images/banner.jpg'),
('rofimata05', 'Milkshake', 4.00, 'rofimata', '/images/banner.jpg'),
('tea01', 'Ζεστό', 2.00, 'tea', '/images/banner.jpg'),
('tea02', 'Ice Tea', 2.00, 'tea', '/images/banner.jpg'),
('beverages01', 'Αναψυκτικά 500ml', 2.00, 'beverages', '/images/banner.jpg'),
('beverages02', 'Amita Χυμοί', 2.00, 'beverages', '/images/banner.jpg'),
('beverages03', 'Ανθρακούχο', 2.00, 'beverages', '/images/banner.jpg'),
('beverages04', 'Redbull', 3.00, 'beverages', '/images/banner.jpg'),
('beverages05', 'Νερό 500ml', 0.50, 'beverages', '/images/banner.jpg'),
('juice01', 'Πορτοκάλι', 3.00, 'juice', '/images/banner.jpg'),
('juice02', 'Ανάμεικτος (φρούτα εποχής)', 3.50, 'juice', '/images/banner.jpg'),
('snacks01', 'Μπακέτα', 2.60, 'snacks', '/images/banner.jpg'),
('snacks02', 'Μπακέτα Γαλοπούλα', 2.60, 'snacks', '/images/banner.jpg'),
('snacks03', 'Τόστ', 2.00, 'snacks', '/images/banner.jpg'),
('snacks04', 'Club Sandwich', 5.50, 'snacks', '/images/banner.jpg'),
('snacks05', 'Club Sandwich Chicken', 6.50, 'snacks', '/images/banner.jpg'),
('snacks06', 'Κοτομπουκιές', 6.50, 'snacks', '/images/banner.jpg'),
('sweets01', 'Παγωτά 1 μπάλα', 2.00, 'sweets', '/images/banner.jpg'),
('sweets02', 'Παγωτά 2 μπάλες', 3.50, 'sweets', '/images/banner.jpg'),
('sweets03', 'Παγωτά extra μπάλα', 1.50, 'sweets', '/images/banner.jpg'),
('sweets04', 'Βάφλα', 4.50, 'sweets', '/images/banner.jpg'),
('sweets05', 'Σουφλέ Σοκολάτας', 6.00, 'sweets', '/images/banner.jpg'),
('sweets06', 'Σοκολατόπιτα', 6.00, 'sweets', '/images/banner.jpg'),
('donuts01', 'Ντόνατ Σοκολάτα', 2.50, 'donuts', '/images/banner.jpg'),
('donuts02', 'Ντόνατ Λευκή Σοκολάτα', 2.50, 'donuts', '/images/banner.jpg'),
('donuts03', 'Ντόνατ Bueno', 2.50, 'donuts', '/images/banner.jpg');
